name: advanced_multi_modular_clean_architecture_bloc
packages:
  - core/**
  - features/**

command:
  bootstrap:
    environment:
      sdk: ">=3.7.0 <4.0.0"
      flutter: ">=3.29.0"

    dependencies:
      dio: ^5.9.2
      get_it: ^8.3.0
      injectable: ^2.5.1
      json_annotation: ^4.9.0


    dev_dependencies:
      injectable_generator: ^2.7.0
      json_serializable: ^6.9.5
      build_runner: ^2.5.4
      flutter_lints: ^5.0.0

scripts:
  clean: melos clean
  cleanAndBootstrap: melos clean && melos bootstrap
  test:
    run: melos exec --concurrency=1 -- flutter test
  update: flutter pub outdated
  upgrader: flutter pub upgrade --major-versions
  lint: flutter pub run flutter_lints:check
